# Miscellaneous
listofstuff = ['backspace_held and not keys[8]:',
'tab_held and not keys[9]:',
'return_held and not keys[13]:',
'pausebreak_held and not keys[19]:',
'escape_held and not keys[27]:',
'space_held and not keys[32]:',
'apostrophe_held and not keys[39]:',
'comma_held and not keys[44]:',
'minus_held and not keys[45]:',
'fullstop_held and not keys[46]:',
'forwardslash_held and not keys[47]:',
# Numbers across the top
'zero_held and not  keys[48]:',
'one_held and not keys[49]:',
'two_held and not keys[50]:',
'three_held and not keys[51]:',
'four_held and not keys[52]:',
'five_held and not keys[53]:',
'six_held and not keys[54]:',
'seven_held and not keys[55]:',
'eight_held and not keys[56]:',
'nine_held and not keys[57]:',
# Miscellaneous,
'semicolon_held and not keys[59]:',
'backslash_held and not keys[60]:',
'equals_held and not keys[61]:',
'opensquarebracket and not keys[91]:',
'sharp_held and not keys[92]:',
'closesquarebracket and not keys[93]:',
'backtick_held and not keys[96]:',
# Alphabet
'a_held and not keys[97]:',
'b_held and not keys[98]:',
'c_held and not keys[99]:',
'd_held and not keys[100]:',
'e_held and not keys[101]:',
'f_held and not keys[102]:',
'g_held and not keys[103]:',
'h_held and not keys[104]:',
'i_held and not keys[105]:',
'j_held and not keys[106]:',
'k_held and not keys[107]:',
'l_held and not keys[108]:',
'm_held and not keys[109]:',
'n_held and not keys[110]:',
'o_held and not keys[111]:',
'p_held and not keys[112]:',
'q_held and not keys[113]:',
'r_held and not keys[114]:',
's_held and not keys[115]:',
't_held and not keys[116]:',
'u_held and not keys[117]:',
'v_held and not keys[118]:',
'w_held and not keys[119]:',
'x_held and not keys[120]:',
'y_held and not keys[121]:',
'z_held and not keys[122]:',
# Miscellaneous,
'delete_held and not keys[127]:',
# Numpad
'numpad0_held and not keys[256]:',
'numpad1_held and not keys[257]:',
'numpad2_held and not keys[258]:',
'numpad3_held and not keys[259]:',
'numpad4_held and not keys[260]:',
'numpad5_held and not keys[261]:',
'numpad6_held and not keys[262]:',
'numpad7_held and not keys[263]:',
'numpad8_held and not keys[264]:',
'numpad9_held and not keys[265]:',
'numpaddivide_held and not keys[267]:',
'numpadmultiply_held and not keys[268]:',
'numpadminus_held and not keys[269]:',
'numpadplus_held and not keys[270]:',
'numpadenter_held and not keys[271]:',
# Arrow keys,
'uparrow_held and not keys[273]:',
'downarrow_held and not keys[274]:',
'rightarrow_held and not keys[275]:',
'leftarrow_held and not keys[276]:',
# Miscellaneous,
'insert_held and not keys[277]:',
'home_held and not keys[278]:',
'end_held and not keys[279]:',
'pageup_held and not keys[280]:',
'pagedown_held and not keys[281]:',
# F keys,
'f1_held and not keys[282]:',
'f2_held and not keys[283]:',
'f3_held and not keys[284]:',
'f4_held and not keys[285]:',
'f5_held and not keys[286]:',
'f6_held and not keys[287]:',
'f7_held and not keys[288]:',
'f8_held and not keys[289]:',
'f9_held and not keys[290]:',
'f10_held and not keys[291]:',
'f11_held and not keys[292]:',
'f12_held and not keys[293]:',
# Key modifiers,
'numlock and not keys[300]:',
'capslock and not keys[301]:',
'scrolllock_held and not keys[302]:',
'rightshift_held and not keys[303]:',
'leftshift_held and not keys[304]:',
'rightcontrol_held and not keys[305]:',
'leftcontrol_held and not keys[306]:',
'altgrammar_held and not keys[307]:',
'alt_held and not keys[308]:',
'leftwindows_held and not keys[311]:',    #} these might be
'rightwindows_held and not keys[312]:',   #} pointless (windows keys)
'menubutton_held and not keys[319]:']

for item in listofstuff:
    for x in range(len(item)):
        if item[x] == " ":
            s = x
            break
    #printable = "if " + item + "\n" +  "    " + item[0:s-5] + " = 1\n" +   "    " + item[0:s] + " = 0"
    #print printable
    print "if " + item[0:s-5] + ":\n" +"    " + "return "+'""'
    
    
    
        
